include:
  - path: ../Cerebritron_CC/docker-compose.yml
  - path: ../Cerebritron_AC/docker-compose.yml
  - path: ../Cerebritron_PS/docker-compose.yml
  - path: ../Cerebritron_SM/docker-compose.yml
  - path: ../Cerebritron_HAL/docker-compose.yml