include:
  - path: ../Cerebritron_CC/cerebritron-cc.yml
  - path: ../Cerebritron_AC/cerebritron-ac.yml
  - path: ../Cerebritron_PS/cerebritron-ps.yml
  - path: ../Cerebritron_SM/cerebritron-sm.yml
  - path: ../Cerebritron_HAL/cerebritron-hal.yml